### PR TITLE
trivial: fix command for installing g++-8

### PR DESCRIPTION
**Pull request by Ivan-Velickovic**

### CODE REVIEW

**Comment by Ivan-Velickovic** [comment]
This error is somewhat interesting since if you're like me and you like to mindlessly install things on computer by copy and pasting commands, `g++8` is interpreted as a regex instead so you end up installing 12 packages that match the regex.

**Review by axel-h — APPROVED** [review]

**Comment by Ivan-Velickovic** [comment]
I may look into that. Another recent grad at TS has made a Nix shell (https://github.com/1000teslas/sel4-nix-shells) for seL4 development, I think it'd be good to have this as an option listed on the website since it's easy for things to get messy when installing natively, for example the use of `update-alternatives`. Although, this is yet another thing to maintain and should probably be a seperate issue/PR for discussion.

**Review by lsf37 — APPROVED** [review]
Thanks for spotting that, this typo was probably my fault.

(ps: please don't leave the PR description empty, even for a trivial one, it's the first place people look at when reviewing)

**Comment by Ivan-Velickovic** [comment]
I’ll add a description from now on, thanks.

**Comment by lsf37** [comment]
> Looks good to me. Once day this could just mention a script that one can executed and that is also used when building the docker containers, so there is an implicit guarantee this works - and there is no redundancy in some documentation that easily gets out of sync

The Debian docs already are pointing to the docker container instead of replicating it, and the Ubuntu description doesn't work on the docker containers (because these are Debian).

But I totally agree that the install docs should be tested, including Ubuntu. We could maybe make a separate docker container that runs those instructions and maybe extract the docs from the docker file or a shell script that runs in the container.

Before we do that, we should update the Ubuntu instructions to 20.04LTS. 18LTS should still work and there is nothing really wrong with it, but if you pick a standard Ubuntu install it'd be 20. Should also slightly simplify the instructions, because more default version should just work.

**Comment by lsf37** [comment]
> Another recent grad at TS has made a Nix shell (https://github.com/1000teslas/sel4-nix-shells) for seL4 development. I think it'd be good to eventually have Nix as an option listed on the website since it's easy for things to get messy when installing natively, for example the use of update-alternatives. Although, this is yet another thing to maintain and should probably be a seperate issue/PR for discussion.

@kent-mcleod might be interested in that, he once made me try nix on MacOS :-)

In general, I'd be fine with that, it would mainly need someone who is willing to answer questions on the mailing list etc for it and test + maintain it. Once it's working maintenance overhead for this one might be fairly low, but I'm not exactly a nix expert.

**Pull request merged**
