### PR TITLE
hardware: make title consistent in page/menus

### PR DESCRIPTION
**Pull request by june-andronick**
Used the term "Supported hardware platforms" (after discussion with Gerwin) for: the Hardware page title, the side menu and the landing page (table of content).

### CODE REVIEW

**Comment by Ivan-Velickovic** [comment]
I have one comment (which might have already been discussed between you two), is it right to refer to the page as 'Hardware' since it also contains simulation platforms? I thought 'Supported Platforms' might be better since it covers both, but maybe it is too vague...

**Comment by june-andronick** [comment]
> I have one comment (which might have already been discussed between you two), is it right to refer to the page as 'Hardware' since it also contains simulation platforms? I thought 'Supported Platforms' might be better since it covers both, but maybe it is too vague...

That's a good point @Ivan-Velickovic . I'm happy to change to just "Supported platforms" everywhere if preferred. @lsf37 : thoughts?

**Comment by lsf37** [comment]
> > I have one comment (which might have already been discussed between you two), is it right to refer to the page as 'Hardware' since it also contains simulation platforms? I thought 'Supported Platforms' might be better since it covers both, but maybe it is too vague...
> 
> That's a good point @Ivan-Velickovic . I'm happy to change to just "Supported platforms" everywhere if preferred. @lsf37 : thoughts?

In principle yes, but we should make sure that the word "hardware" is mentioned prominently enough on the page so that Google returns it as top link for searches like "seL4 hardware".

**Comment by june-andronick** [comment]
> Thanks @lsf37 . Does it mean you're ok with this PR? If so can you approve? Else let me know what you'd like to see happening before. Thanks!

@lsf37 ping :)

**Review by lsf37 — APPROVED** [review]

**Pull request merged**
