### PR TITLE
rfc: fix RFC dashboard link

### PR DESCRIPTION
**Pull request by lsf37**
The old RFC dashboard had a broken issue filter and was not editable any more. Replace with a new, working dashboard.

### CODE REVIEW

**Comment by corlewis** [comment]
The new dashboard isn't accessible for me
```
We can’t show that dashboard

Someone may have deleted it, renamed it, or you don’t have access. 
```

**Comment by lsf37** [comment]
> The new dashboard isn't accessible for me

Apologies. I thought I had saved the permissions, but apparently not. Can you try again? (Jira is such a joy..)

**Comment by corlewis** [comment]
> > The new dashboard isn't accessible for me
> 
> Apologies. I thought I had saved the permissions, but apparently not. Can you try again? (Jira is such a joy..)

Unfortunately, still not.

**Comment by lsf37** [comment]
> > > The new dashboard isn't accessible for me
> > 
> > 
> > Apologies. I thought I had saved the permissions, but apparently not. Can you try again? (Jira is such a joy..)
> 
> Unfortunately, still not.

Ok, one more (last?) time..

**Comment by corlewis** [comment]
> > > > The new dashboard isn't accessible for me
> > > 
> > > 
> > > Apologies. I thought I had saved the permissions, but apparently not. Can you try again? (Jira is such a joy..)
> > 
> > 
> > Unfortunately, still not.
> 
> Ok, one more (last?) time..

Success! However, now it looks like the filter requires permissions as well.
```
The requested filter doesn't exist or is private.
```

**Review by corlewis — APPROVED** [review]
The new dashboard is working for me now!
My only potential concern is if there are other links floating around to the old one, but I don't think that there's much we can about that if there are.

**Comment by lsf37** [comment]
> The new dashboard is working for me now! My only potential concern is if there are other links floating around to the old one, but I don't think that there's much we can about that if there are.

At least on the doc site I haven't found any. There might of course be some out in the general internets, but not much we can do about that. If you find any specific ones, let me know!

**Pull request merged**
