### PR TITLE
dependencies: downgrade sass-embedded for docker

### PR DESCRIPTION
**Pull request by lsf37**
The current docker file does not build with sass-embedded 1.63. Downgrade the dependency for now. Longer term we should upgrade what is installed in the docker file.

### CODE REVIEW

**Comment by lsf37** [comment]
The CI build is broken for a different reason, fixed (hopefully) in #212

**Comment by lsf37** [comment]
Actually this does not seem to properly fix it. Let me have another look.

**Comment by Indanz** [comment]
I tested the docs site with Ruby 2.7, not sure what's going on.

**Comment by lsf37** [comment]
It's the environment in the docker file. The error message is:
```
#6 70.29 Fetching gem metadata from https://rubygems.org/.........
#6 74.41 sass-embedded-1.63.6-aarch64-linux-musl requires rubygems version >= 3.3.22,
#6 74.41 which is incompatible with the current version, 3.1.6
```
So the `rubygems` version from `ruby:2` in docker is too old.

The downgrade does actually seem to fix it, I was just on the one branch when I wrote the message above.

**Comment by lsf37** [comment]
(I tried just building it from `ruby:3` in docker, but that leads to other conflicts)

**Review by june-andronick — APPROVED** [review]

**Comment by Indanz** [comment]
The x86 version of `sass-embedded-1.63.6` seems to work fine with Ruby 2.7, so it must be an aarch64-linux-musl thing.

**Comment by lsf37** [comment]
> The x86 version of `sass-embedded-1.63.6` seems to work fine with Ruby 2.7, so it must be an aarch64-linux-musl thing.

That actually makes sense, because I'd assume the aarch64 version is more recent, so might need more recent dependencies.

**Comment by Indanz** [comment]
> That actually makes sense, because I'd assume the aarch64 version is more recent, so might need more recent dependencies.

That would mean that the version depends on the platform, making Gemfiles not portable. I consider that a bug.

**Comment by lsf37** [comment]
> > That actually makes sense, because I'd assume the aarch64 version is more recent, so might need more recent dependencies.
> 
> That would mean that the version depends on the platform, making Gemfiles not portable. I consider that a bug.

Yes, I think that's what's happening.

**Pull request merged**
