### PR TITLE
Fix broken edit URLs

### PR DESCRIPTION
**Pull request by kent-mcleod**
This also provides a fix for #55

### CODE REVIEW

**Review by lsf37 — APPROVED** [review]
Looks very good. Have you tested locally? We should really add some CI for the docs site, but one thing at a time..

**Comment by kent-mcleod** [comment]
I have tested this locally.  The deployment plan for this also generates a diff of the generated site in the logs, which someone could look at to validate what changed

**Comment by lsf37** [comment]
Just spotted a small difference: the path for the "normal" GitHub view/edit link had space characters in it and would fail for me -- removing the indentation inside `{{capture}}` worked.

There is one small last bit: the edit link for the included file is now at the top of the page, whereas the standard edit link is in the footer. I'm not sure if/how it's possible to transport the info from the include file to the footer template in Jekyll, but I'll have a brief look if I can find something that'd do that.

**Comment by kent-mcleod** [comment]
> Just spotted a small difference: the path for the "normal" GitHub view/edit link had space characters in it and would fail for me -- removing the indentation inside {{capture}} worked.

Weird.  I tested it, added the indentation to try make it more readable, then thought I tested it again...

> There is one small last bit: the edit link for the included file is now at the top of the page, whereas the standard edit link is in the footer. I'm not sure if/how it's possible to transport the info from the include file to the footer template in Jekyll, but I'll have a brief look if I can find something that'd do that.

Well, the tutorial page is comprised of 2 pages, hence the 2 links.  I followed the same pattern as other pages: https://docs.sel4.systems/projects/capdl/translator.

**Comment by lsf37** [comment]
> > Just spotted a small difference: the path for the "normal" GitHub view/edit link had space characters in it and would fail for me -- removing the indentation inside {{capture}} worked.
> 
> Weird. I tested it, added the indentation to try make it more readable, then thought I tested it again...

Might also be a platform/version difference (testing this on Mac)


> Well, the tutorial page is comprised of 2 pages, hence the 2 links. I followed the same pattern as other pages: https://docs.sel4.systems/projects/capdl/translator.

Right, that has a similar problem. We could just put it at the bottom of the page (like on the capDL page), then it's at least closer to the other edit button. I'm still not sure I would see it if I didn't know, but at least it's closer.

I haven't found anything easy yet, because you can't pass variable values out from the included file into the footer template. We'd have to capture everything inside the footer, but there are probably too many different cases to do this nicely.

**Comment by lsf37** [comment]
I'll add a commit for putting the link at the bottom, so you can have a look if you like it.

**Comment by lsf37** [comment]
Ok, added. If you're happy with that, this would be ready to merge from my side.

**Comment by kent-mcleod** [comment]
Sure.

**Comment by lsf37** [comment]
👍

**Pull request merged**
