### PR TITLE
Added instructions to TFTP boot on RPI 3B+

### PR DESCRIPTION
**Pull request by fabriziobertocci**
TFTP boot works only for RPI 3B, not 3B+. For 3B+ you need to rebuild u-boot but is not a straight forward process as the defconfig for the 3B+ fails. This change explain the steps to build a working u-boot image for the 3B+ so you can use TFTP to boot seL4 image

### CODE REVIEW

**Comment by mbrcknl** [comment]
Hi @fabriziobertocci, thanks for your contribution! I hope you don't mind that I force pushed to your branch, just to squash the commits and wrap the text in the commit message.

However, before I can merge this, I'll need you to do the DCO sign-off, since that's your declaration that you have the authority to contribute this work under the relevant license. The best way to see how to do that is to follow the "Details" link next to the failing DCO check. As soon as you've done that, I'll merge this.

**Review by mbrcknl — APPROVED** [review]

**Comment by fabriziobertocci** [comment]
Thanks Matthew,
I've pushed the amended message with the signoff.
But shouldn't have signed off all the messages (and not the last commit)?

**Comment by fabriziobertocci** [comment]
I tried multiple time to follow the instructions on how to fix the DCO problem.
I am giving up.

**Comment by axel-h** [comment]
Just squash all you commits into one. After the commit message's body text append a linebreak and the string "Signed-off-by: Signed-off-by: Fabrizio Bertocci <fabriziobertocci@gmail.com>" there.

**Comment by fabriziobertocci** [comment]
Axel,
I followed the instructions in github:
https://github.com/seL4/docs/pull/83/checks?check_run_id=2962654827
The command:
git rebase HEAD~11 --signoff
keeps producing conflicts even if there was no real conflict (all the
conflicting lines were the same).
After manually resolving them, I commit them and I keep getting the same
error.
I have spent way too much time fighting github. Enough is enough. I only
added a few lines to a .md file.

I closed the PR.

Fab

**Comment by axel-h** [comment]
I've squashed thing here and made a new PR, see https://github.com/seL4/docs/pull/87 in case we want to merge this.

**Comment by fabriziobertocci** [comment]
Thank you Axel!
Regards,
Fabrizio

**Comment by mbrcknl** [comment]
I'm sorry @fabriziobertocci, I dropped the ball on this one! I'm glad Axel was able to pick it up for you.

**Pull request closed without merging**
