### PR TITLE
hardware: add page for ultra96v2

### PR DESCRIPTION
**Pull request by chrisguikema**
Added a page for the ultra96v2 since its a supported seL4 platform, and doesn't have a page on the website.

### CODE REVIEW

**Review by axel-h — APPROVED** [review]
looks good to me

**Comment by chrisguikema** [comment]
Should be noted that I needed to add a commit to seL4_tools to actually get sel4test compiling for the ultra96v2, but that shouldn't stop this from getting merged.

**Comment by axel-h** [comment]
See https://github.com/seL4/seL4_tools/pull/152

**Comment by chrisguikema** [comment]
> Do you happen to know if this board is available again? 

Last I saw there was a 52-week lead time. I hadn't realized they stopped production.

**Review by lsf37 — APPROVED** [review]

**Pull request merged**
