### PR TITLE
roles: update reviewer+committer lists

### PR DESCRIPTION
**Pull request by lsf37**
Syncing committers list, adding Indan to reviewers.

### CODE REVIEW

**Comment by lsf37** [comment]
@indanz is MEP correct as affiliation?

**Comment by Indanz** [comment]
> @Indanz is MEP correct as affiliation?

Yes, but only till the end of this year, so for three more weeks. After that I'm off to Tasmania for four months and after that I'm moving from The Netherlands to Ireland and need to find a new job and house.

**Comment by Indanz** [comment]
As a side note, although I'm leaving MEP next year, I will keep their use case and interest in mind, so in that sense I will still be affiliated with them, although not officially.

Aren't the TCS members missing from the list? Or at least mention what role/access they all have.

**Comment by lsf37** [comment]
> > @Indanz is MEP correct as affiliation?
> 
> Yes, but only till the end of this year, so for three more weeks. After that I'm off to Tasmania for four months and after that I'm moving from The Netherlands to Ireland and need to find a new job and house.

Ok, let's leave it in for now and then update it when it has changed (you can make a pull request directly).

> Aren't the TCS members missing from the list? Or at least mention what role/access they all have.

They are listed on a separate page (linked from here): https://sel4.systems/Foundation/TSC/

**Review by gernotheiser — APPROVED** [review]

**Comment by Indanz** [comment]
> > Aren't the TCS members missing from the list? Or at least mention what role/access they all have.
> 
> They are listed on a separate page (linked from here): https://sel4.systems/Foundation/TSC/

I know, but that doesn't say what access they have on Github. Perhaps only some TSC members have committer or sysadmin rights. Considering this info is not mentioned, I assume they have all the mentioned rights, but it is not obvious from the text.

**Comment by lsf37** [comment]
> > > Aren't the TCS members missing from the list? Or at least mention what role/access they all have.
> > 
> > 
> > They are listed on a separate page (linked from here): https://sel4.systems/Foundation/TSC/
> 
> I know, but that doesn't say what access they have on Github. Perhaps only some TSC members have committer or sysadmin rights. Considering this info is not mentioned, I assume they have all the mentioned rights, but it is not obvious from the text.

Got it. TSC members have at least Committer rights, I'll add that to the page.

**Pull request merged**
